### PR TITLE
Fixed the grid card label not fitting in the linearLayout

### LINKED ISSUE #213: [BUG] Text not fitting in the card when browsing albums
**Describe the bug**
The artist name may not fit in the cards when browsing albums :
- In the albums menu 
- In the artist's albums menu.
It depends of the text size defined in the Android device settings.

**To Reproduce**
1. Go to Android device settings > Accessibility > Display size and text
2. Increase the Font size option until you notice fit problem in the app, on my device it happens pretty quickly (value >= 2)

**Expected behavior**
The card should expend depending the height of the text inside (album + artist), to avoid cutting it from the bottom. So far, it seems only the artist name in impacted.

**Screenshots**
Screenshot_20240701-023536
Screenshot_20240701-023618

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 14
 - App Version: 1.0.8.04a37e

**Additional context**
None.

### PR DESCRIPTION
**Pull request by kuroi-9**
Resolves #213 
Hopefully I didn't miss the point of setting the linearLayout height to `@dimen/grid_card_label_height`...

Even with the android device Font size set to the maximum, I can't reproduce the issue anymore.

### CODE REVIEW

**Comment by nift4** [comment]
Right now, this will break fast-scrolling. The code needs to know the height in advance to be able to map scroll bar progress to the proper item. https://github.com/AkaneTan/Gramophone/blob/6d35176c6b8e1065198817970074f9f0c1911c12/app/src/main/kotlin/org/akanework/gramophone/ui/adapters/BaseAdapter.kt#L385-L412
Tbh I don't like that code anyway but I did not find a better solution so far. Regarding the font scaling issue, I suppose a fix would be making label height a `sp` unit, but I'm not sure as I haven't tried yet.

**Comment by kuroi-9** [comment]
Oh so that's what this code is doing, I didn't understood it when I went across it 😅 thanks for the explanation.
I'll continue to experiment on my side.

**Comment by nift4** [comment]
Hey, sorry, I didn't get to this yet, but due to high amount of PRs, Akane is preparing a new release. I didn't forget it

**Comment by nift4** [comment]
The issue is now fixed, if you have more issues (or the fix doesn't work for you) just let me know :)

**Pull request closed without merging**
