### PR TITLE
added a HorizontalScrollView around crash logs text and a share FAB to the activity

### PR DESCRIPTION
**Pull request by N3Shemmy3**
this is to allow crash logs text to scroll horizontally

### CODE REVIEW

**Comment by nift4** [comment]
@N3Shemmy3 are you sure they aren't rn?

**Comment by N3Shemmy3** [comment]
Screenshot_20240419-172630_Gramophone
yes i am sure

**Comment by N3Shemmy3** [comment]
added a share fab, its string, and drawable resources and its backend

**Comment by nift4** [comment]
1 please remove the HorizontalScrollView i still dont think its a good idea
2 app/src/main/res/layout/activity_bug_handler.xml has a lot of reformat changes (tab 4->8) that aren't needed
otherwise looks good

**Comment by N3Shemmy3** [comment]
@nift4 How about the strings.xml? Is the formatting correct now?

**Comment by nift4** [comment]
@N3Shemmy3 yes

**Comment by N3Shemmy3** [comment]
@nift4 I've removed the horizontal scroll view and "hopefully" undid the formatting

**Pull request merged**
