### PR TITLE
Rearrange Titles in Queue Using Gestures

### PR DESCRIPTION
**Pull request by topazrn**
Implement #154

### CODE REVIEW

**Comment by nift4** [comment]
Hi, thanks for this PR - not updating the unshuffled index will cause playlist to be out of sync like in the bug you reported, but i'll commit a fix

**Comment by topazrn** [comment]
Oops, I didn't notice there was such a thing. Thanks for the incoming fix!

**Comment by nift4** [comment]
It turned out to be a little more complicated, I'll commit a fix some other day

**Comment by nift4** [comment]
This lead me to discover some bugs in our shuffle implementation, thanks for that :P

**Pull request merged**
