### PR TITLE
Add support StatusBarLyric

### PR DESCRIPTION
**Pull request by ghhccghk**
Screenshot_20241023-220543
Screenshot_20241023-220613
Support effect viewing

### CODE REVIEW

**Comment by nift4** [comment]
Hi,

thanks for the PR :)
how can I test MeiZu API, is there Xposed module about it?
What's the difference between MeiZu and Lyric Getter API?

**Comment by ghhccghk** [comment]
> Hi,
> 
> thanks for the PR :) how can I test MeiZu API, is there Xposed module about it? What's the difference between MeiZu and Lyric Getter API?

For the Meizu status bar, you need to find a device using the Flyme system or a quasi-native system that supports lyrics in the status bar. The difference from the xpoesd module is that this module can support systems that do not support lyrics in the status bar through the module. The difference is this

**Comment by ghhccghk** [comment]
Lyric Getter API The lyric getter module can be tested, but the source code needs to be modified to change to the Meizu status bar lyrics hook mode. The PR I submitted for lyric getter is in api mode. That's all I can say for now. I have to go to work tomorrow. Sorry, I have to go to bed.

**Comment by nift4** [comment]
Thanks for the info!

**Comment by ghhccghk** [comment]
I use translation software I use translation software which may cause problems with the sentencesI'm sorry about that.

**Comment by nift4** [comment]
You can answer whenever you have time, no hurry.

Is there a disadvantage of disabling api mode in Lyric-Getter json and only using MeiZu mode in Gramophone & delete API code compared to using API mode?

**Comment by ghhccghk** [comment]
> You can answer whenever you have time, no hurry.
> 
> Is there a disadvantage of disabling api mode in Lyric-Getter json and only using MeiZu mode in Gramophone & delete API code compared to using API mode?


There's no difference, just a difference in the way you get the lyrics

**Comment by nift4** [comment]
In that case, can you please delete Lyric Getter API code and change the PR in Lyric Getter repo to disable API mode?
After that, I will merge this PR.

**Comment by ghhccghk** [comment]
> In that case, can you please delete Lyric Getter API code and change the PR in Lyric Getter repo to disable API mode? After that, I will merge this PR.

Yes, but I need a few days to optimize the code

**Comment by nift4** [comment]
Sounds good, thank you!

**Comment by ghhccghk** [comment]
What I want to ask here is how to pass extras into the playback notification, so that you don’t have to create a separate notification and open the notification at the same time.

**Comment by nift4** [comment]
You can extend this class:
https://developer.android.com/reference/androidx/media3/session/DefaultMediaNotificationProvider

https://github.com/AkaneTan/Gramophone/blob/9534f6e3c4f7a04ce3a6a17afd2af9e758d12b6b/app/src/main/kotlin/org/akanework/gramophone/logic/GramophonePlaybackService.kt#L186

**Comment by ghhccghk** [comment]
> You can extend this class: https://developer.android.com/reference/androidx/media3/session/DefaultMediaNotificationProvider
> 
> https://github.com/AkaneTan/Gramophone/blob/9534f6e3c4f7a04ce3a6a17afd2af9e758d12b6b/app/src/main/kotlin/org/akanework/gramophone/logic/GramophonePlaybackService.kt#L186

Thanks for providing the method, but there is no interface I want. Currently, I can only solve it by adding a status bar lyrics notification. The disadvantage is that you have to turn on the notification.

**Comment by nift4** [comment]
Hi, it's fine, I will optimize the media3 playback notification later, can you upload a version with seperate notification?

**Comment by ghhccghk** [comment]
> Hi, it's fine, I will optimize the media3 playback notification later, can you upload a version with seperate notification?

Yes, but you have to wait until I complete the code.

**Comment by ghhccghk** [comment]
It's basically done and ready to be merged, also can you give me the next version number so I can change it in the lyric getter?

**Comment by nift4** [comment]
Thank you! Next version code will be 17

**Comment by nift4** [comment]
Kindly ignore Akane, I'll fix it...

**Comment by ghhccghk** [comment]
> Kindly ignore Akane, I'll fix it...

Then it looks like I suck at code.

**Comment by nift4** [comment]
His problem is mostly chinese comment and untranslatable text I think

**Comment by ghhccghk** [comment]
> His problem is mostly chinese comment and untranslatable text I think

I'll fix it.

**Comment by nift4** [comment]
Hi, I have changed the code to DefaultMediaNotificationProvider and enabled status bar lyric in latest commit. Thank you for your contribution :)

**Comment by ghhccghk** [comment]
> Hi, I have changed the code to DefaultMediaNotificationProvider and enabled status bar lyric in latest commit. Thank you for your contribution :)

I currently found a Meizu device to test the status bar lyrics, but found some problems
This is the device information interface. Since the user is a Chinese native speaker, the interface is in Chinese.
mmexport1729919884812
This is a screenshot of the lyrics test in the status bar, one line faster than expected.
mmexport1729920022398
Crash occurs when not using the new lyrics interface

**Comment by nift4** [comment]
Hi, thank you, I think I have fixed the problem. Can you try again with new commit?

**Comment by ghhccghk** [comment]
> Hi, thank you, I think I have fixed the problem. Can you try again with new commit?

It's perfectly fine, but the lyrics won't refresh, I'm troubleshooting the problem

**Comment by nift4** [comment]
If the lyrics won't refresh with Lyric Getter Xposed, maybe need to hook the `setForegroundServiceNotification`.
On Flyme OS, I hope it will work.

**Comment by ghhccghk** [comment]
> If the lyrics won't refresh with Lyric Getter Xposed, maybe need to hook the `setForegroundServiceNotification`. On Flyme OS, I hope it will work.

Totally, but please update agp to 8.7.0 and then don't confuse androidx.media3.common.util.

**Comment by ghhccghk** [comment]
> > If the lyrics won't refresh with Lyric Getter Xposed, maybe need to hook the `setForegroundServiceNotification`. On Flyme OS, I hope it will work.
> 
>
 Totally, but please update agp to 8.7.0 and then don't confuse androidx.media3.common.util.Util

**Comment by nift4** [comment]
I just pushed new commit.

https://github.com/AkaneTan/Gramophone/blob/0d88ef121b1f1b048de2f8312fe521656df74d1b/app/proguard-rules.pro#L33

Is this what you meant?

**Comment by ghhccghk** [comment]
> I just pushed new commit.
> 
> https://github.com/AkaneTan/Gramophone/blob/0d88ef121b1f1b048de2f8312fe521656df74d1b/app/proguard-rules.pro#L33
> 
> Is this what you meant?

Yes

**Comment by nift4** [comment]
Great, thanks for you work. :)
Will the Lyric Getter work fine now?
Will the Flyme OS also work fine?
Or do I need to change the code?

**Comment by ghhccghk** [comment]
> Great, thanks for you work. :) Will the Lyric Getter work fine now? Will the Flyme OS also work fine? Or do I need to change the code?

All work

**Comment by nift4** [comment]
Great, thank you!!

**Comment by ghhccghk** [comment]
> Great, thank you!!
Work photos
Screenshot_20241026-191142_留声机

**Pull request merged**
