### PR TITLE
drop android:fitsSystemWindows, use a better way to add insets

### PR DESCRIPTION
**Pull request by lightsummer233**
add applicationIdSuffix, reformat some codes, update deps

known issue: status bar part of the material toolbar will blink under elevated state

https://github.com/AkaneTan/Gramophone/assets/93428659/3f717c44-7b0a-40bd-9665-ae7f3a38773e

### CODE REVIEW

**Comment by nift4** [comment]
why not use fitsSystemWindows?

**Comment by lightsummer233** [comment]
> why not use fitsSystemWindows?

when use fitsSystemWindows
Screenshot_2024-02-23-15-44-02-379_org akanework gramophone
Screenshot_2024-02-22-23-39-56-646_org akanework gramophone
Screenshot_2024-02-22-23-40-22-182_org akanework gramophone

**Comment by nift4** [comment]
what exactly is the problem? the navbar background?

**Comment by lightsummer233** [comment]
> what exactly is the problem? the navbar background?

Yes

**Comment by lightsummer233** [comment]
And the color of the appbar does not extend to the screen notch before

IMG_20240223_155543
IMG_20240223_155526

**Comment by nift4** [comment]
I fixed the navbar issue here: f72157e341334303c8f4a3f95041aed3063e86e9
I'll fix the top app bar thing too in a way that's hopefully a little less manual code

**Comment by lightsummer233** [comment]
Screenshot_2024-02-23-16-27-08-265_org akanework gramophone
Can you fix the inset issue on Xiaomi HyperOS freeform？

**Comment by nift4** [comment]
fixed settings inset in c57baa4c6cc0c778de8679ac2e0da7952d4f4b4f pls try again

**Comment by nift4** [comment]
@lightsummer233 can you check if its still broken?

**Comment by lightsummer233** [comment]
> @lightsummer233 can you check if its still broken?

still not fixed
the bottom line of freeform is not a navbar
u can get the height of this via use `insets.getInsets(WindowInsetsCompat.Type.captionBar()).bottom`
and the ... on top of freeform is not a status bar
I think u should use `insets.getInsets(WindowInsetsCompat.Type.systemBars()).bottom` for the bottom inset of freeform

or the better way, use `Insets.max(insets.getInsets(WindowInsetsCompat.Type.systemBars()), insets.getInsets(WindowInsetsCompat.Type.displayCutout()))` for it

I don't know if you can understand it. I'm not good at English

**Comment by lightsummer233** [comment]
The insets of bottom sheet also broken
Please fix it, thanks

**Comment by nift4** [comment]
Hi, please try 869bc1b

**Comment by lightsummer233** [comment]
> Hi, please try [869bc1b](https://github.com/AkaneTan/Gramophone/commit/869bc1b77851b4e564d6aa764bc99b08433d26ff)

The issue of insets on HyperOS freeform has already been fixed, thanks. 
But your fix also has this issue:
> status bar part of the material toolbar will blink under elevated state

**Comment by lightsummer233** [comment]
And the bottom sheet also has a issue like this:

https://github.com/AkaneTan/Gramophone/assets/93428659/5c672546-1718-4e23-ac32-7a3af19ebd59

**Comment by nift4** [comment]
Interestingly enough, the status bar issue seems to be normal.
Thank you for the valuable information regarding captionBars() it solved the HyperOS issue :)
Sadly I believe the bottom sheet issue is hard to fix for me as I don't have XiaoMi device, and it does not happen in AOSP freeform

**Pull request closed without merging**
